version: 2
jobs:
  checkout_code:
    docker:
      - image: node:8.4.0
    working_directory: ~/wellcomecollection.org
    steps:
      - checkout
      - save_cache:
          key: repo_{{ .Environment.CIRCLE_SHA1 }}
          paths:
            -  ~/wellcomecollection.org
  install_server_modules:
    docker:
      - image: node:8.4.0
    working_directory: ~/wellcomecollection.org/server
    steps:
      - restore_cache:
          key: repo_{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Install server package
        command: npm install --production
      - save_cache:
          key: server_modules_{{ .Environment.CIRCLE_SHA1 }}
          paths:
            -  ~/wellcomecollection.org/server/node_modules
  test:
    docker:
      - image: node:8.4.0
    working_directory: ~/wellcomecollection.org
    steps:
    - restore_cache:
        key: repo_{{ .Environment.CIRCLE_SHA1 }}
    - restore_cache:
        key: server_modules_{{ .Environment.CIRCLE_SHA1 }}
    - run:
        name: Test server
        command: pushd server && npm run test && popd
  build:
    docker:
      - image: node:8.4.0
    working_directory: ~/wellcomecollection.org
    steps:
      - restore_cache:
          key: repo_{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: server_modules_{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Build client
          command: ./build-client.sh
      - run:
          name: Build server
          command: ./build-server.sh $CIRCLE_BUILD_NUM
      - add_ssh_keys
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.1-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Install AWS CLI
          command: |
            # Taken from
            # http://docs.aws.amazon.com/cli/latest/userguide/awscli-install-linux.html
            apt-get -y -qq update
            apt-get -y -qq install python3.4-dev
            curl -O https://bootstrap.pypa.io/get-pip.py
            python3.4 get-pip.py --user
            export PATH=~/.local/bin:$PATH
            pip install awscli --upgrade --user
      - run:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              # Install AWS CLI. Taken from:
              # http://docs.aws.amazon.com/cli/latest/userguide/awscli-install-linux.html
              apt-get -y -qq update
              apt-get -y -qq install python3.4-dev
              curl -O https://bootstrap.pypa.io/get-pip.py
              python3.4 get-pip.py --user
              export PATH=~/.local/bin:$PATH
              pip install awscli --upgrade --user

              docker build -t wellcome/wellcomecollection:$CIRCLE_BUILD_NUM .
              docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
              docker push wellcome/wellcomecollection:$CIRCLE_BUILD_NUM

              pushd nginx-proxy && ./docker-build.sh $CIRCLE_BUILD_NUM && ./docker-push.sh $CIRCLE_BUILD_NUM && popd
              pushd router && ./docker-build.sh $CIRCLE_BUILD_NUM && ./docker-push.sh $CIRCLE_BUILD_NUM && popd

              ./build-cardigan.sh
              ./build-speedtracker.sh
            fi
  lint:
    docker:
      - image: node:8.4.0
    working_directory: ~/wellcomecollection.org/linter
    steps:
      - restore_cache:
          key: repo_{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Install deps
          command: npm install
      - run:
          name: Lint
          command: ./lint.sh
workflows:
  version: 2
  build_and_lint:
    jobs:
      - checkout_code
      - install_server_modules
      - test:
          requires:
            - checkout_code
            - install_server_modules
      - build:
          requires:
            - checkout_code
            - test
      - lint:
          requires:
            - checkout_code
